# Generated by Django 2.0 on 2019-12-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickblocks', '0002_auto_20191225_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickblock',
            name='color',
            field=models.CharField(blank=True, help_text='A background color to use for the image, in the format: #rrggbb', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='content',
            field=models.TextField(blank=True, help_text='The body of text for this content block, optional', null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblock_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Any image that should be displayed with this content block, optional', null=True, upload_to='quickblocks'),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='link',
            field=models.CharField(blank=True, help_text='Any link that should be associated with this content block, optional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblock_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='priority',
            field=models.IntegerField(default=0, help_text='The priority for this block, higher priority blocks come first'),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='quickblock_type',
            field=models.ForeignKey(help_text='The category, or type for this content block', on_delete=django.db.models.deletion.CASCADE, to='django_quickblocks.QuickBlockType', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='summary',
            field=models.TextField(blank=True, help_text='The summary for this item, should be short', null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='tags',
            field=models.CharField(blank=True, help_text='Any tags for this content block, separated by spaces, can be used to do more advanced filtering, optional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='title',
            field=models.CharField(blank=True, help_text='The title for this block of content, optional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickblock',
            name='video_id',
            field=models.CharField(blank=True, help_text='The id of the YouTube video that should be linked to this item', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickblockimage',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblockimage_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblockimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='quickblock_images/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='quickblockimage',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblockimage_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='created_by',
            field=models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblocktype_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='description',
            field=models.TextField(blank=True, help_text='A description of where this content type is used on the site and how it will be dsiplayed', null=True),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_color',
            field=models.BooleanField(default=False, help_text='Whether this content has a color field'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_gallery',
            field=models.BooleanField(default=False, help_text='Whether this content should allow upload of additional images, ie a gallery'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_image',
            field=models.BooleanField(default=True, help_text='Whether this content should include an image'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_link',
            field=models.BooleanField(default=True, help_text='Whether this content should include a link'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_rich_text',
            field=models.BooleanField(default=True, help_text='Whether this content should use a rich HTML editor'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_summary',
            field=models.BooleanField(default=True, help_text='Whether this content should include a summary field'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_tags',
            field=models.BooleanField(default=False, help_text='Whether this content should allow tags'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_title',
            field=models.BooleanField(default=True, help_text='Whether this content should include a title'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='has_video',
            field=models.BooleanField(default=False, help_text='Whether this content should allow setting a YouTube id'),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='django_quickblocks_quickblocktype_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='name',
            field=models.CharField(help_text='The human readable name for this content type', max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='quickblocktype',
            name='slug',
            field=models.SlugField(help_text='The slug to idenfity this content type, used with the template tags', unique=True),
        ),
    ]
